=head1 NAME

show_wp_versions.pl

=head1 SYNOPSIS

Lists the websites currently configured in the copy of Apache running
on this system. If a website is configured to run Wordpress in one of
a few standard locations, the version of Wordpress is displayed. If that
version of Wordpress was checked out of a Subversion repository, the
tagged or trunk version is displayed as well.

=head1 USAGE

$ ./show_wp_versions.pl  [domain_regexp]

  domain_regexp, if supplied, will act only on domains matching.

      Default: sort by domain name
               (subdomain names have low priority in the sort)

 -l   Long format: include template and plugin report ~~~ unfinished
 -n   Sort by numeric version number
 -t   Sort by Subversion date/time
 -e   Sort by domain expiration date
 -u   Sort by owning UID

 -a   Display all domain names, even ones we do not have read permission
 -b   Create SQL backup files in /tmp
 -U   Force database upgrades via wget

=head1 LICENSE

Copyright © William Lindley <wlindley@wlindley.com>

All rights reserved. This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.
